---
output: pdf_document
header-includes: \usepackage{graphicx}
---

Recurrence Quantification Analysis as a Framework for Statistical Natural Language Processing
====================================================================================

Recurrence quantification analysis (RQA) is a method most commonly used to study noisy and continuously varying physical systems. RQA provides a suite of measures to describe the dynamic patterns present in a time series measured from these systems. It is used in two general and closely related ways. The first is to estimate invariant characteristics underlying a dynamic system. The second is to obtain more general statistical measures to describe systems or compare systems to each other. 

In the former case, RQA is used as a tool that can precisely determine the type of system that is being studied. For example...

In the latter case, RQA is used for similar purposes, but one remains more agnostic about the specific underlying properties of the system. Instead, this use of RQA seeks more general characteristics. Is one system more or less regularly structured in time? How prolonged are a system's persistent states or trajectories? What is the most stable regime the system exhibits in time? These questions have been prominently posed in psychology, for example, in characterizing postural dynamics under different conditions. Posture is a noisy and continuously varying signal, and RQA has allowed researchers to explore postural stability in various ways (Riley et al.; Balasubramaniam et al.).
















